### ISSUE TITLE
SORMAS_DOCKER_VERSION=2.10.2 not on Docker Hub

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Docker#105]
Hi,
on `develop`, `.env` contains the SORMAS_DOCKER_VERSION=2.10.2 variable, however, this version is not published on Docker Hub. The latest available version tag there is `2.10.1`. Can you fix or publish the version? 

Best,
Jonas

**Comment by nliakm** [comment]
v2.10.2 had some major issues. Please install v2.10.3 instead.
