### ISSUE TITLE
Update From 1.46.0 to 1.47.1

### ISSUE THREAD

**Issue by Abdi-Abdallah** [hzi-braunschweig/SORMAS-Docker#108]
Hello,

We have issue when we update from 1.46.0 to 1.47.1 on prod environnent.
All container created except apache2.
We have this error below:

compose.parallel.feed_queue: Pending: {<Service: apache2>}
compose.cli.verbose_proxy.proxy_callable: docker containers <- (all=False, filters={'label': ['com.docker.compose.project=sormas-docker', 'com.docker.compose.service=sormas', 'com.docker.compose.oneoff=False']})
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.30/containers/json?limit=-1&all=0&size=0&trunc_cmd=0&filters=%7B%22label%22%3A+%5B%22com.docker.compose.project%3Dsormas-docker%22%2C+%22com.docker.compose.service%3Dsormas%22%2C+%22com.docker.compose.oneoff%3DFalse%22%5D%7D HTTP/1.1" 200 1917
compose.cli.verbose_proxy.proxy_callable: docker containers -> (list with 1 items)
compose.cli.verbose_proxy.proxy_callable: docker inspect_container <- ('121678c8f776f16aa24e6fe408a7e57b2f10e8ad9a98c4ee2118ee49d8aca3b4')
urllib3.connectionpool._make_request: http://localhost:None "GET /v1.30/containers/121678c8f776f16aa24e6fe408a7e57b2f10e8ad9a98c4ee2118ee49d8aca3b4/json HTTP/1.1" 200 None
compose.cli.verbose_proxy.proxy_callable: docker inspect_container -> {'AppArmorProfile': '',
'Args': [],
'Config': {'AttachStderr': False,
            'AttachStdin': False,
            'AttachStdout': False,
            'Cmd': ['/start-server.sh'],
            'Domainname': '',
            'Entrypoint': None,
            'Env': ['SORMAS_POSTGRES_USER=sormas_user',
                    'SORMAS_POSTGRES_PASSWORD=XXXXX',

We have:
debian 9.12

# docker-compose version
docker-compose version 1.25.5, build 8a1c60f6
docker-py version: 4.1.0
CPython version: 3.7.5
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

# docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:26:02 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Best regards,

Fayçal

**Comment by bernardsilenou** [comment]
@TomHutter Please can you have a look at this issue? It is from the french dev team, they are currently blocked and urgently need to upgrade.
Please tag me for further comment or if further information is needed.
Thanks you
