### ISSUE TITLE
postgres container doesn't start - IOError: [Errno 2] No such file or directory: '/sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us'

### ISSUE THREAD

**Issue by licks0re** [hzi-braunschweig/SORMAS-Docker#131]
Good morning,

When updating to the last version, I hit the problem mentionned in the title.

The following error repeats again and again :

**postgres_1  | Traceback (most recent call last):
postgres_1  |   File "/usr/local/bin/alter_system.py", line 143, in <module>
postgres_1  |     sys.exit(main(sys.argv))
postgres_1  |   File "/usr/local/bin/alter_system.py", line 139, in main
postgres_1  |     values = get_tuning_values(config, options.tuning_config)
postgres_1  |   File "/usr/local/bin/alter_system.py", line 101, in get_tuning_values
postgres_1  |     cpu = get_cpu()
postgres_1  |   File "/usr/local/bin/alter_system.py", line 77, in get_cpu
postgres_1  |     cpu_quota = int(get_cgroup_resources("/sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us"))
postgres_1  |   File "/usr/local/bin/alter_system.py", line 62, in get_cgroup_resources
postgres_1  |     with open(file, 'r') as proc_fil:
postgres_1  | IOError: [Errno 2] No such file or directory: '/sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us'**

I saw DB_CPUS=2.0 from .env file and the call to the var in docker-compose.yml is gone as well, maybe this is linked ?

Of course I checked if the file was there: 

```
postgres_1  | IOError: [Errno 2] No such file or directory: '/sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us'
[root@sormas_dev SORMAS-Docker]# ll /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us
-rw-r--r--. 1 root root 0 Sep 14 11:20 /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us
[root@sormas_dev SORMAS-Docker]# 
```

[root@sormas_dev SORMAS-Docker]# docker -v
**Docker version 1.13.1, build 64e9980/1.13.1**
[root@sormas_dev SORMAS-Docker]# docker-compose -v
**docker-compose version 1.18.0, build 8dd22a9**
[root@sormas_dev SORMAS-Docker]# more /etc/os-release
**NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"**

Thanks in advance for your lights on this,
Gui

**Comment by licks0re** [comment]
Hello,

Just to let you know, exact same problem on a clean install of centos7 with last version of the code.

postgres_1  | Traceback (most recent call last):
postgres_1  |   File "/usr/local/bin/alter_system.py", line 143, in <module>
postgres_1  |     sys.exit(main(sys.argv))
postgres_1  |   File "/usr/local/bin/alter_system.py", line 139, in main
postgres_1  |     values = get_tuning_values(config, options.tuning_config)
postgres_1  |   File "/usr/local/bin/alter_system.py", line 101, in get_tuning_values
postgres_1  |     cpu = get_cpu()
postgres_1  |   File "/usr/local/bin/alter_system.py", line 77, in get_cpu
postgres_1  |     cpu_quota = int(get_cgroup_resources("/sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us"))
postgres_1  |   File "/usr/local/bin/alter_system.py", line 62, in get_cgroup_resources
postgres_1  |     with open(file, 'r') as proc_fil:
postgres_1  | IOError: [Errno 2] No such file or directory: '/sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us'

**Comment by licks0re** [comment]
Nobody else have this problem??

**Comment by nliakm** [comment]
It could be related to the docker version you are using (docker from the centos repo is far behind the official docker version). I suggest you to use the official repo from docker to install the latest version:
https://docs-stage.docker.com/engine/install/centos/

**Comment by licks0re** [comment]
Thanks a lot nliakm, 

This stupid outdate version on centos repo was indeed the problem... Can't believe it, I search in all direcitons but this one, I didn't think centos repo was such outdated...

And there's so much misleading article online I didn't go through that direction!

Thanks again, problem solved.

Gui

**Comment by licks0re** [comment]
By the way, after update, I faced this error :

```
Error response from daemon: Unknown runtime specified docker-runc
Error: failed to start containers: (...)
```

So I had to do a :

`docker system prune -a `

to restart with fresh containers and it worked smoothly.

**Comment by nliakm** [comment]
Good to hear, that this was indeed the problem!
I strongly suggest you to follow the first step from the [docker documentation](https://docs-stage.docker.com/engine/install/centos/#uninstall-old-versions) and delete all prior installed packages related to docker to prevent any strange behavior:
```
sudo yum remove docker \
                  docker-client \
                  docker-client-latest \
                  docker-common \
                  docker-latest \
                  docker-latest-logrotate \
                  docker-logrotate \
                  docker-engine
```
