### ISSUE TITLE
How to backup Database & how to update the Docker-Container

### ISSUE THREAD

**Issue by chrisseiner** [hzi-braunschweig/SORMAS-Docker#151]
As the title states i'd lile to know how can i acces the database (using psql?) and how can i backup the databse.
Also I'd like to know how to update the docker-container without setting up a new instance with updated version.

**Comment by JonasCir** [comment]
Hi @chrisseiner :
With default settings this will work: `psql --host=localhost -U postgres sormas

Not sure what mean with second point. The intended way is to stop the deployment bump the docker-compose.yml and the .env file to the new version and restart. The data is persisted via the volumes so there is no data loss in the update

**Comment by nliakm** [comment]
Regarding the backup: The service **pg_dump** periodically dumps the two databases **sormas** and **sormas_audit** to the `/backup` folder of the docker host. It will keep the last 10 dumps and delete all older ones. If you want to keep older backups, make sure to save them to another directory (e.g. with a cronjob) before they get deleted.
