### ISSUE TITLE
Update to 1.52.1

### ISSUE THREAD

**Issue by Abdi-Abdallah** [hzi-braunschweig/SORMAS-Docker#156]
Hello,

We have an issue when  updating to to 1.52.1.
Sormas stop at query bellow:

Updating database to version 281... (de.symeda.sormas.backend.common.StartupShutdownService.java:598) 

UPDATE epidata SET contactwithsourcecaseknown = 'YES' FROM cases WHERE cases.epidata_id = epidata.id AND (SELECT COUNT(id) FROM contact WHERE contact.resultingcase_id = cases.id) > 0

We use sormas, apache2 in container with external bdd in another server 

The same update in another environment take 30min
Could you help us?

Best Regards,

Abdi Abdallah

**Comment by carolinverset** [comment]
@bernardsilenou 

As mentioned this morning and as indicated in this issue, Integra is unable to install 1.52.1 on our test environment (volume of data similar to our production environment). Could you tag the person who could inform Bertrand Bassoulet's team? It's quite urgent as you can imagine

**Comment by bernardsilenou** [comment]
I would create a copy of this issue in the main repository and link it to this.

**Comment by bernardsilenou** [comment]
This is the lint to the issue in the main repo 
https://github.com/hzi-braunschweig/SORMAS-Project/issues/3926

**Comment by nliakm** [comment]
Closed since the referenced issue is also closed.
