### ISSUE TITLE
daysAfterCaseGetsArchived appears not be set in SORMAS-Docker

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Docker#167]
See https://github.com/hzi-braunschweig/SORMAS-Project/issues/4201

Some while ago I took already a look and IIRC `daysAfterCaseGetsArchived` property is not set in `.env` and not written to the config file with `sed`. This results in the property being empty and not configurable.

### How to fix this

Add `daysAfterCaseGetsArchived` to `.env` and insert into property file.

**Comment by JonasCir** [comment]
Hey please consider to fix this in the new release, under some circumstances this message spams the logs making Debugging quite unpleasant and inefficient.

**Comment by nliakm** [comment]
This property has now a default value set in the .env
