### ISSUE TITLE
disable default entities with property (user + infrastructure data like district etc)

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Docker#168]
@TomHutter There is a new server property called ~~`createDefaultUsers`~~ `createDefaultEntities.` If it is false, then no default users will be populated to the DB on startup. @T-Hundt told me that this is a pain point for you. See https://github.com/hzi-braunschweig/SORMAS-Project/issues/4129

Best

---

Edit the property is now called `createDefaultEntities`

**Comment by JonasCir** [comment]
It will go into the very next release

**Comment by JonasCir** [comment]
@asohh The last release happened so this should be in the new Docker version I guess?

**Comment by nliakm** [comment]
This option is now configurable since 2.20.0 via `CREATE_DEFAULT_ENTITIES` environment.
