### ISSUE TITLE
Compose Script creates virtual Network 172.18.0.0 masking real network

### ISSUE THREAD

**Issue by psymagic** [hzi-braunschweig/SORMAS-Docker#174]
While installig SORMAS at our institute, I've been surprisingly shut out of my Server. Neither SSH nor Ping worked.

After a logging in from a diffrent client, the cause was clear: My workstation is 172.18.48.134/23
When Sormas creates its internal Network (172.18.0.0/18), the real one is masked.

Where is this configuration set and how can I change it? I couldnt find it in the compose-files.
Also 172.18.0.0/18 seems unessecary large in scope, making such collisions more likely.

**Comment by nliakm** [comment]
You can edit the /etc/docker/daemon.json to configure docker to use a pre defined address pool (via the option default-address-pools), so it won't collide with your internal network:
https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-configuration-file
