### ISSUE TITLE
new gdpr feature

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Docker#198]
See this PR https://github.com/hzi-braunschweig/SORMAS-Project/pull/4856

The GDPR feature is disabled by default now, so you need to reenable it for German systems

**Comment by nliakm** [comment]
This needs to be done by the administrator of the SORMAS instance.
To re-enable the feature, cd to the path, where the docker-compose file is located and enter following command:
```
sudo docker-compose exec postgres psql -U sormas_user sormas --command "update featureconfiguration set enabled = true,changedate = now() where featuretype = 'GDPR_CONSENT_POPUP'"
```

**Comment by JonasCir** [comment]
So that is not in the server property files?

**Comment by nliakm** [comment]
Correct. This is a feature that has to be switched on/off directly inside the database. Before we can set as an environment via the sormas.properties, this has to be added in the SORMAS-Project first.
