### ISSUE TITLE
[postgres] alter_system.py does not use memory and cpu limits

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Docker#201]
Read this comment for update:
https://github.com/hzi-braunschweig/SORMAS-Docker/issues/201#issuecomment-829046545

---
Old description:

The return values of `get_mem` and `get_cpu` are unused:
```python
def get_tuning_values(config, filename):
    mem = get_mem()
    cpu = get_cpu()
```
and therefore the functions should be removed

### Why is this a problem anyway?
Well, the Linux Kernel. Apparently my last OS update switched to [cgroup v2](https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html) which has a completely different layout of `/sys/fs/cgroup/` and files like e.g., `memory/memory.limit_in_bytes` are gone, renamed, or replaced causing `alter_system.py` to fail.

### How to resolve the issue
1. Delete `get_mem` and `get_cpu` as these functions are not used
2. Use the return values but then we need to future proof the logic

**Comment by JonasCir** [comment]
@asohh @TomHutter Any comment on this? I'm happy to provide a PR to remove the functions. Being unable to use the official docker image really complicates my workflows and cost a lot of time, it would be great to resolve this with the next release

**Comment by norpol** [comment]
Those values are actually in use, they are parsed from `tuning_parameters.conf` via  https://github.com/hzi-braunschweig/SORMAS-Docker/blob/38bd63daccf4278868a99261c4e4e1ba1a8f8450/postgres/docker-entrypoint.sh#L317

It's just that those cgroup memory limits are not set for everyone and therefor failing. Script should be adjusted to fallback to non-limits.

**Comment by JonasCir** [comment]
Hm maybe we are talking about to different things :D
https://github.com/hzi-braunschweig/SORMAS-Docker/blob/master/postgres/alter_system.py#L99
In the first two lines, the variables `mem` and `cpu` are assigned with the return value of `get_mem()`/`get_cpu`. The invocation of these functions triggers the error on `cgroupv2` Linux systems. I cannot see, that the variables `mem` and `cpu` are used after assignment at all in `get_tuning_values()` and my IDE also shows them as unused.

There are 2 ways to make sure the `postgres` starts on recent Linux host systems: Remove `get_cpu/mem` or rewrite the logic in such a way that all versions of cgroup can be handled correctly

**Comment by norpol** [comment]
Sorry I was a bit short with my description, the variable appear to be unassigned - that is correct but it is actually "dynamically" used by

https://github.com/hzi-braunschweig/SORMAS-Docker/blob/38bd63daccf4278868a99261c4e4e1ba1a8f8450/postgres/alter_system.py#L120

if you print these lines you'll see that `mem` and `cpu` are indeed in use. The exec will run those within python scope, that's something quite unconventional and I'm not sure what postgres suggestion for running in docker is for tweaking the configuration without some sophisticated code like that.

```python
values['work_mem'] = int(mem / max_connections)
values['maintenance_work_mem'] = int(mem / 16)
values['wal_buffers'] = int(mem * 3 / 400)
values['max_worker_processes'] = int(cpu)
values['max_parallel_workers_per_gather'] = int(cpu / 2)
values['max_parallel_workers'] = int(cpu)
```

**Comment by JonasCir** [comment]
@norpol Thanks for the clarification! :) Alright now I see.

**Comment by JonasCir** [comment]
@TomHutter @asohh @T-Hundt 
Can you please prioritize this? More and more people are creating their own patched version b/c the official release is broken.

**Comment by TomHutter** [comment]
Hi all, sorry for the late reply. As you see in the log, I added a a commit a few minutes ago. Please have a look at it. I tested it with cgroups v2 as well as with cgroups v1. Feedback appreciated :-)

**Comment by norpol** [comment]
Hey @TomHutter , looks good to me. Trying to understand the code I ended up refactoring it instead, but not much a difference in the end. Bummer how much manual efforts you need to go through when you start configuring cgroup limits.

https://github.com/hzi-braunschweig/SORMAS-Docker/pull/221/files

Anyway, thanks for fixing it!

**Comment by JonasCir** [comment]
Thank you @TomHutter :+1:

**Comment by nliakm** [comment]
Merged into the latest release candidate.
