### ISSUE TITLE
How to access the dockerized web server from the local network?

### ISSUE THREAD

**Issue by gdeflaux** [hzi-braunschweig/SORMAS-Docker#21]
Hi,

I've managed to spin up the docker containers and access the web app from server it run on, but I can't access it from any other computer from the same LAN. This prevents me from testing the web application.

Could you help me solve this, please? We ([Alima](https://www.alima-ngo.org/en/)) are in the process of testing the application to support our COVID response in several countries and testing the mobile app is a critical aspect, as you can imagine!

Thanks!

G.

**Comment by asohh** [comment]
Hey

Have you checked the firewall configuration of the Dockerhost?

**Comment by gdeflaux** [comment]
Hi,

I've ran `sudo ufw disable` (ubuntu) to make sure there was nothing blocking the access. I've also tried with other dockerized apps and it works fine. Is there anything else I should consider firewall-wise?

Thanks for your help!

**Comment by asohh** [comment]
We recommend to allow the ports 80 and 443 on the firewall

**Comment by gdeflaux** [comment]
Hi,

They should be open:

![Screenshot from 2020-04-09 19-00-14](https://user-images.githubusercontent.com/223608/78920895-60712e00-7a94-11ea-8fd0-772b1f3e7b78.png)

On the browser on my phone, I get an ERR_NAME_NOT_RESOLVED. The url in the browser is `https://sormas-docker-test.com`. Is there anything I should do with the `hosts` file on the docker host (beyond what is indicated in the README)?

Cheers,

**Comment by asohh** [comment]
Since the hostname isn't set in a DNS server the phone can't resolve the server.

To resolve this you can create a local DNS server and use that one on the phone to resolve the host

**Comment by gdeflaux** [comment]
Ok thanks.

**Comment by asohh** [comment]
You are welcome.

Did my suggestion fix your problem?
