### ISSUE TITLE
Updating with existing Database did not enable extension unaccent

### ISSUE THREAD

**Issue by OlafDoering** [hzi-braunschweig/SORMAS-Docker#218]
Updating a sormas installation using the docker distribution with a version v2.20.0-rc1 or later did not activate the needed extension unaccent in postgresql.

For new installations this is done in /docker-entrypoint-initdb.d/setup_sormas.sh, triggered from  docker-entrypoint.sh in _main().

After update and login, sormas is showing an error and server.log is saying: 
Caused by: org.postgresql.util.PSQLException: ERROR: function unaccent(character varying) does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.

**Comment by nliakm** [comment]
All new installations will have all the desired extensions installed.
But if there are new extension required, these must be installed manually on existing installations before the update.
We will always note in the release notes, if additional actions are required: https://github.com/hzi-braunschweig/SORMAS-Docker/releases/tag/v2.20.0
