### ISSUE TITLE
Version 2.19.1 throwing cpu related error

### ISSUE THREAD

**Issue by JohnTheBeloved** [hzi-braunschweig/SORMAS-Docker#222]
I am trying to run the `2.19.1` version

`docker-compose` is failing to start the sormas-postgres service

MacOS Catalina 10.15.7
docker-compose version 1.29.1, build c34c88b2
Docker version 20.10.6, build 370c289

Please find error log of error below

![image](https://user-images.githubusercontent.com/7778212/117654636-ec6cf200-b18d-11eb-8998-0cfc21c66727.png)

`Attaching to rtsl-dashboard_sormas-db_1
sormas-db_1         | 
sormas-db_1         | Traceback (most recent call last):
sormas-db_1         |   File "/usr/local/bin/alter_system.py", line 143, in <module>
sormas-db_1         |     sys.exit(main(sys.argv))
sormas-db_1         |   File "/usr/local/bin/alter_system.py", line 139, in main
sormas-db_1         |     values = get_tuning_values(config, options.tuning_config)
sormas-db_1         |   File "/usr/local/bin/alter_system.py", line 101, in get_tuning_values
sormas-db_1         |     cpu = get_cpu()
sormas-db_1         |   File "/usr/local/bin/alter_system.py", line 77, in get_cpu
sormas-db_1         |     cpu_quota = int(get_cgroup_resources("/sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us"))
sormas-db_1         |   File "/usr/local/bin/alter_system.py", line 62, in get_cgroup_resources
sormas-db_1         |     with open(file, 'r') as proc_fil:
sormas-db_1         | IOError: [Errno 2] No such file or directory: '/sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us'`

**Comment by licks0re** [comment]
Hello John,

I think it's not a Sormas error but a docker version problem.

Check this link where I reported the same error : 
https://github.com/hzi-braunschweig/SORMAS-Docker/issues/131

Solution provided by Nliakm : 
https://github.com/hzi-braunschweig/SORMAS-Docker/issues/131#issuecomment-729034652

Check this link with instructions to install last docker version on Mac :
https://docs.docker.com/docker-for-mac/install/

Hope it helps,
Gui

**Comment by nk-designz** [comment]
Hi @JohnTheBeloved,
as @licks0re already said it might be an old docker version
or even a general incompatibility with docker for mac.

The easiest way to success would be to move to a good old linux VM :)

Have a nice day.
