### ISSUE TITLE
Long term solution for fixed postgres:10.16-alpine

### ISSUE THREAD

**Issue by tnako-sg** [hzi-braunschweig/SORMAS-Docker#245]
This is due to error during setting up of temporal_tables 1.2.0 extention.
Currently the workaround is to keep postgres fixed (frozen) version which may lead to security vunerabilities and potential incompatibility problems in the future.  Root cause solution has to be found.

**Comment by tnako-sg** [comment]
After research the reason was found and the bug is caused by recent changes in musl library referred here:
https://gitlab-test.alpinelinux.org/alpine/aports/-/issues/12321

It could be eradicated by upgrading docker system version to more recent 20.10.3.
Which is long term solution (1).

**Comment by tnako-sg** [comment]
Since it is not always possible switch to a newer docker version... another solution (2) is to introduced:
https://github.com/hzi-braunschweig/SORMAS-Docker/pull/246
It keeps fixed version of musl and musl-dev library - instead of freezing the whole postgres image version to 10.16-alpine.

**Comment by nliakm** [comment]
Is now merged.
