### ISSUE TITLE
restoring database from a backup

### ISSUE THREAD

**Issue by licks0re** [hzi-braunschweig/SORMAS-Docker#26]
Good afternoon,

How do you restore a backup into sormas db ?
I managed to empty database by droping table one by one, but when I restore using I can't see my cases and data.

I use this command to restore from a backup : 

`psql -h localhost -p 5432 -U my_user -d my_database  -f  /backups/backupfile.sql`

Any idea? Or is there and other procedure to restore a backup?

Thanks in advance,

Guillaume

**Comment by asohh** [comment]
hey


The procedure is like this:
1. stop all containers
2. delete directory of Postgres
3. start postgres container (using the docker-compose file)
4. import both backups into the databases
5. start sormas containers
