### ISSUE TITLE
 Notification of a task: Display of the UUID of the object concerned by the notification in the form of a hyperlink that cannot be activated in a docker environment

### ISSUE THREAD

**Issue by carolinverset** [hzi-braunschweig/SORMAS-Docker#305]
A recent french development has improved the content of the notification sent to the user when a task is assigned to him. Indeed, this notification now includes a link that directs the user directly to the object concerned by the task. This feature must be enabled in the properties file.

In a standard non-docker environment, this element can be easily configured in the properties file.
- URL of the SORMAS UI
- Will be used in email and SMS notifications to link to a specific page.
- ui.url = https: //sormas-std.test.esante-bfc.fr/sormas-ui/

On the other hand, it is not possible to apply it in the docker version because this variable cannot be defined via the ".env" file which allows you to define the docker environment. By modifying it by hand in the docker, the service must be restarted, which has the consequence of overwriting this modification ...

@ftavin @bernardsilenou

**Comment by bernardsilenou** [comment]
@fhauptmann @TomHutter 
Any idea about how this can be adjusted in the docker version of the app?

**Comment by carolinverset** [comment]
@fhauptmann @bernardsilenou @olivierleuci 
Following the development of France consisting in including in the notification a hypertext link to the object concerned by the task, we would like to make it available to users if possible. However, in a docker environment, it is not possible to activate this feature. Can you adapt the .env file accordingly?

**Comment by fhauptmann** [comment]
@carolinverset thanks for your request. We are currently evaluating the issue and opened a story in the project. We still need to get approvement from product owner to integrate this request.

**Comment by fhauptmann** [comment]
@carolinverset we created a technical story in the backlog from this request. We will close this story.

**Comment by carolinverset** [comment]
@fhauptmann 
Thank you very much !
