### ISSUE TITLE
apache log file in /usr/local/

### ISSUE THREAD

**Issue by HolgerReiseVSys** [hzi-braunschweig/SORMAS-Docker#32]
In https://github.com/hzi-braunschweig/SORMAS-Project/issues/1876#issuecomment-618638809 it was noted that there is an issue with `ErrorLog /usr/local/apache2/error.log` in [vhost.conf.sh](https://github.com/hzi-braunschweig/SORMAS-Docker/blob/master/apache2/vhost.conf.sh).

I suppose `ErrorLog /var/log/apache2/error.log` would be correct.
This would be consistent with [SERVER_SETUP.md](https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/SERVER_SETUP.md#apache-web-server).

**Comment by asohh** [comment]
This has been changed in version 2.0.3
