### ISSUE TITLE
Unable to login into an informant role

### ISSUE THREAD

**Issue by juusotam** [hzi-braunschweig/SORMAS-Docker#33]
I am evaluating SORMAS for production use. With a fresh Docker installation of SORMAS (1.38.0) I am unable to login as an informant role (hospital informant or community informant). I have tried to create new users with this role only.

```
Error message: HTTP 403 Forbidden
Type: Status report
Message: Forbidden
Description: Access to the specific resource has been forbidden
```

Any idea what might be causing this?

**Comment by asohh** [comment]
Hey

I think your question hast to be answered by the SORMAS-Project team. @MartinWahnschaffeSymeda Maybe you can help him.

But I could imagine that the roles you chose don't have access to the WebUI. (Some users only have access to the API)

**Comment by MartinWahnschaffeSymeda** [comment]
@asohh is right. The informant does not have access to the web app - it's a user role to be used with the mobile device only.
I'd suggest to use a surveillance supervisor instead, to get started.

**Comment by juusotam** [comment]
Thanks!
