### ISSUE TITLE
ERROR: manifest for docker.io/hzibraunschweig/sormas-postgres:2.0.1 not found

### ISSUE THREAD

**Issue by licks0re** [hzi-braunschweig/SORMAS-Docker#38]
After git pull to new update, I'm getting this error:

[root@SORMAS-Docker]# docker-compose up -d
Pulling postgres (hzibraunschweig/sormas-postgres:2.0.1)...
Trying to pull repository docker.io/hzibraunschweig/sormas-postgres ...
ERROR: manifest for docker.io/hzibraunschweig/sormas-postgres:2.0.1 not found

Anybody can help ?

**Comment by licks0re** [comment]
I confirm the bug, same error on fresh install :

[root@host SORMAS-Docker]# docker-compose up
Creating network "sormasdocker_default" with the default driver
Pulling postgres (hzibraunschweig/sormas-postgres:2.0.1)...
Trying to pull repository docker.io/hzibraunschweig/sormas-postgres ...
ERROR: manifest for docker.io/hzibraunschweig/sormas-postgres:2.0.1 not found

**Comment by asohh** [comment]
Hey,

we had the same Problem with a an old Version of docker.

We changed our Build process in Version 2.0.0 to buildah, which by default pushes the Manifests in the OCI format. Now we added the flag to push the manifest in the v2s1 format 

Currently we are building the dockerimages and well test with Docker on CentOS 7 again afterwards.

**Comment by asohh** [comment]
I just testet it using Docker version 1.13.1, build 64e9980/1.13.1

Now it should also work for you

**Comment by licks0re** [comment]
> I just tested it using Docker version 1.13.1, build 64e9980/1.13.1
> 
> Now it should also work for you

Thanks asohh!
I confirm the issue is fixed.

```
[root@host SORMAS-Docker]# docker-compose up
Pulling postgres (hzibraunschweig/sormas-postgres:2.0.2)...
Trying to pull repository docker.io/hzibraunschweig/sormas-postgres ...
2.0.2: Pulling from docker.io/hzibraunschweig/sormas-postgres
cbdbe7a5bc2a: Pull complete
(...)
```


I'm using centos 7 with exact same docker version you buid!

Thanks again for resolving this issue quickly !
