### ISSUE TITLE
MAP_ZOOM correction

### ISSUE THREAD

**Issue by TexGG** [hzi-braunschweig/SORMAS-Docker#40]
There is an error in "sormas/start-server.sh" : 
`sed -i "s/map.zoom=.*/map.zoom=${map_zoom}/" ${DOMAIN_DIR}/sormas.properties` should be replace with `sed -i "s/map.zoom=.*/map.zoom=${MAP_ZOOM}/" ${DOMAIN_DIR}/sormas.properties` or it will never found the variable since its called "MAP_ZOOM" in docker-compose.yml

**Comment by asohh** [comment]
Thank you, we changed that in the containers
