### ISSUE TITLE
ERROR: for apache2  Container "47e59a81ffad" is unhealthy.

### ISSUE THREAD

**Issue by licks0re** [hzi-braunschweig/SORMAS-Docker#57]
When pulling any version since heathcheck implementation:

```

>  docker-compose up
Creating network "sormasdocker_default" with the default driver
Pulling postgres (hzibraunschweig/sormas-postgres:2.3.0)...
Trying to pull repository docker.io/hzibraunschweig/sormas-postgres ...
2.3.0: Pulling from docker.io/hzibraunschweig/sormas-postgres
cbdbe7a5bc2a: Already exists
b52a8a2ca21a: Already exists
e36a19831e31: Already exists
1675b9c16a84: Pull complete
6cd046780b56: Pull complete
3151e81f51cc: Pull complete
227acbe840e2: Pull complete
d5a3d7760a5d: Pull complete
75423e07c65b: Pull complete
61f11714d884: Pull complete
Digest: sha256:d6d90f1fea3d809aabb9e43cd8787c702a49a7c0f02ada7fd2c37c893698f771
Status: Downloaded newer image for docker.io/hzibraunschweig/sormas-postgres:2.3.0
Pulling sormas (hzibraunschweig/sormas-application:2.3.0)...
Trying to pull repository docker.io/hzibraunschweig/sormas-application ...
2.3.0: Pulling from docker.io/hzibraunschweig/sormas-application
6cf436f81810: Already exists
987088a85b96: Already exists
b4624b3efe06: Already exists
d42beb8ded59: Already exists
3cffe3a0ebeb: Already exists
e2f27ac6352a: Already exists
586784844e09: Pull complete
28b2f4e5837f: Pull complete
6eff36c08ef5: Pull complete
Digest: sha256:6e1b61bac5c1534a539933a82382fe70c991624545c887222ff583613859d8c5
Status: Downloaded newer image for docker.io/hzibraunschweig/sormas-application:2.3.0
Pulling pg_dump (hzibraunschweig/sormas-pg-dump:2.3.0)...
Trying to pull repository docker.io/hzibraunschweig/sormas-pg-dump ...
2.3.0: Pulling from docker.io/hzibraunschweig/sormas-pg-dump
486039affc0a: Already exists
df1133812a24: Pull complete
Digest: sha256:388013376170445186bb488bb09dcb986211ede379b2a33e52fafc52c336ee31
Status: Downloaded newer image for docker.io/hzibraunschweig/sormas-pg-dump:2.3.0
Pulling apache2 (hzibraunschweig/sormas-apache2:2.3.0)...
Trying to pull repository docker.io/hzibraunschweig/sormas-apache2 ...
2.3.0: Pulling from docker.io/hzibraunschweig/sormas-apache2
cbdbe7a5bc2a: Already exists
d675277ceb41: Already exists
05d6ddf7a817: Already exists
0da22ef96744: Already exists
5f950d770af2: Already exists
5c9c8f6d4e5f: Pull complete
Digest: sha256:bbcc1c2aaeb511eb9afbee888716958b024a01a37c4bd9a7a3d4863dd4a9be38
Status: Downloaded newer image for docker.io/hzibraunschweig/sormas-apache2:2.3.0
Pulling autoheal (willfarrell/autoheal:latest)...
Trying to pull repository docker.io/willfarrell/autoheal ...
latest: Pulling from docker.io/willfarrell/autoheal
256b99a4c608: Pull complete
4e374d3a23b1: Pull complete
1ee505e19e22: Pull complete
Creating sormasdocker_postgres_1 ... done
Digest: sha256:3e4cdc9fe76859e373d6d968059a54abc8b96f7fac2374d0191059848b6ad666
Status: Downloaded newer image for docker.io/willfarrell/autoheal:latest
Creating sormasdocker_sormas_1   ... done
Creating sormasdocker_pg_dump_1  ... done
Creating sormasdocker_sormas_1   ...
Creating sormasdocker_pg_dump_1  ...

ERROR: for apache2  Container "47e59a81ffad" is unhealthy.
ERROR: Encountered errors while bringing up the project.
```

**Comment by licks0re** [comment]
As a comnplement, a bit later, after asystem update and a reboot, I got that :

```
ERROR: for sormasdocker_sormas_1  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)

ERROR: for sormas  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).
```

Then, next try is same error as above.


I'm running Centos 7, last updates.

**Comment by licks0re** [comment]
Completing again :

Removing the autoheal for container apache works of course.

Can you enlight me on what the test line does ?

 test: ["CMD", "curl", "-f", "-I", "-k", "--resolve", "${SORMAS_SERVER_URL}:443:127.0.0.1", "https://${SORMAS_SERVER_URL}/downloads/"]

 
_${SORMAS_SERVER_URL}:443:127.0.0.1_ ??



I see also a lot of 

```
autoheal_1  | Monitoring containers for unhealthy status in 0 second(s)
autoheal_1  | jq: error (at <stdin>:0): Cannot iterate over number (400)
```

**Comment by licks0re** [comment]
So, apparently, it's a timeout error or something. I can make it work but I can't figure out why it's not working. wo, launching 2docker-compose up" qill fail, see above, but launching containers 1 by 1 will work. (and autoheal last).

What do you think of that?

```
[root@sormasdev01 SORMAS-Docker]# docker-compose ps
Name   Command   State   Ports
------------------------------
[root@sormasdev01 SORMAS-Docker]# docker-compose up -d sormas
Creating sormasdocker_postgres_1 ... done
Creating sormasdocker_postgres_1 ...
Creating sormasdocker_sormas_1   ... done
[root@sormasdev01 SORMAS-Docker]# docker-compose up -d pg_dump
sormasdocker_postgres_1 is up-to-date
Creating sormasdocker_pg_dump_1  ... done
[root@sormasdev01 SORMAS-Docker]# docker-compose up -d apache2
sormasdocker_postgres_1 is up-to-date
sormasdocker_sormas_1 is up-to-date
Creating sormasdocker_apache2_1  ... done
[root@sormasdev01 SORMAS-Docker]# docker-compose up -d autoheal
Creating sormasdocker_autoheal_1 ... done
[root@sormasdev01 SORMAS-Docker]# docker-compose ps
         Name                        Command               State                    Ports
-----------------------------------------------------------------------------------------------------------
sormasdocker_apache2_1    /tmp/vhost.conf.sh /usr/lo ...   Up      0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
sormasdocker_autoheal_1   /docker-entrypoint autoheal      Up
sormasdocker_pg_dump_1    /entrypoint.sh /usr/sbin/c ...   Up
sormasdocker_postgres_1   docker-entrypoint.sh -c co ...   Up      0.0.0.0:5432->5432/tcp
sormasdocker_sormas_1     /start-server.sh                 Up      6048/tcp, 6080/tcp
[root@sormasdev01 SORMAS-Docker]#
```

I hope it's the good place here to troubleshoot and discuss (with myself for the moment :) ). I guess it's the appropriate place so others who encounter same issue see the progress.

If it's not the place, please notify me and I'll stop posting.

Guillaume

**Comment by licks0re** [comment]
Finaly got it to work on my environment.

Because sormas container takes some time to start, the autoheal was causing the sormas container to loop restart and then its status not being healthy when apache2 container started to boot up.

So I update two values in the docker-compose.yml file.


Hope it helps if someone faces the same problem.


`  apache2:
    restart: unless-stopped
    labels:
      - autoheal=true
    links:
      - sormas
    image: hzibraunschweig/sormas-apache2:${SORMAS_DOCKER_VERSION}
    environment:
      - SORMAS_SERVER_URL=${SORMAS_SERVER_URL}
      - TZ=${TZ}
    volumes:
      - ./apache2/certs:/usr/local/apache2/certs
      - ${SORMAS_PATH}/apache2_log:/var/log/apache2
    ports:
      - 443:443
      - 80:80
    cpus: ${WEBSERVER_CPUS}
    mem_limit: ${WEBSERVER_MEM}
    mem_reservation: ${WEBSERVER_MEM_RESERVED}
    healthcheck:
      test: ["CMD", "curl", "-f", "-I", "-k", "--resolve", "${SORMAS_SERVER_URL}:443:127.0.0.1", "https://${SORMAS_SERVER_URL}/downloads/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s
    depends_on:
      sormas:
        condition: **service_started**
`

` autoheal:
    restart: unless-stopped
    image: willfarrell/autoheal
    environment:
        # watch all running containers.
      - AUTOHEAL_CONTAINER_LABEL=all
        # check every 10 seconds
      **- AUTOHEAL_INTERVAL=500**
        # wait 0 seconds before first health check
      - AUTOHEAL_START_PERIOD=0
        # Docker waits max 10 seconds (the Docker default) for a container to stop before killing
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
        # Unix socket for curl requests to Docker API
      - DOCKER_SOCK=/var/run/docker.sock
        # --max-time seconds for curl requests to Docker API
      - CURL_TIMEOUT=30
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
`


Now it works fine. Hope it helps if someone faces the same problem.
I'll leave open for a few days if someone wants to comment, then close the issue.


```

[root@sormasdev01 SORMAS-Docker]# docker ps
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                    PORTS                                      NAMES
8e4caada6362        hzibraunschweig/sormas-apache2:2.3.0       "/tmp/vhost.conf.s..."   39 minutes ago      Up 39 minutes (healthy)   0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   sormasdocker_apache2_1
92e021655bf4        hzibraunschweig/sormas-application:2.3.0   "/start-server.sh"       39 minutes ago      Up 39 minutes (healthy)   6048/tcp, 6080/tcp                         sormasdocker_sormas_1
22c9fcef8ed3        hzibraunschweig/sormas-pg-dump:2.3.0       "/entrypoint.sh /u..."   39 minutes ago      Up 39 minutes                                                        sormasdocker_pg_dump_1
cb722a2c1f58        hzibraunschweig/sormas-postgres:2.3.0      "docker-entrypoint..."   39 minutes ago      Up 39 minutes (healthy)   0.0.0.0:5432->5432/tcp                     sormasdocker_postgres_1
2d7c998c371e        willfarrell/autoheal                       "/docker-entrypoin..."   39 minutes ago      Up 39 minutes (healthy)                                              sormasdocker_autoheal_1

```

**Comment by TomHutter** [comment]
Hi Guillaume,

I can not reproduce the error you are describing. In my environment the apache container waits for the sormas app to be ready (which can take several minutes) and then starts without any errors.

I would disadvise to use a auto heal interval of 500 seconds. Adding the time of the health check, before it signals the container unhealthy it will take about 10 minutes, before a container gets restarted due to an error.

To answer your question what does the command test: ["CMD", "curl", "-f", "-I", "-k", "--resolve", "${SORMAS_SERVER_URL}:443:127.0.0.1", "https://${SORMAS_SERVER_URL}/downloads/"] ?

It tells curl to map the URL ${SORMAS_SERVER_URL} Port 443 to localhost (127.0.0.1). So when calling https://${SORMAS_SERVER_URL}/downloads/" the request is not against the external IP but against 127.0.0.1.

So the test is against https://some.sormas.domain/downloads/ using localhost. The apache Webserver then can do it's name based virtual host mapping ( for some.sormas.domain ) and route the request to the /download location.

Parameters:
-f => curl exits with an error code, if the response is 40x or 50x
-I => do only a head request
-k => ignore invalid ssl cert

This test should be successful, once the apache is up and running.

**Comment by licks0re** [comment]
Hi Tom,

Thanks for the feedback. 
That's strange in your env, you don't have the problem. I have the prob on my dev server and on my production one. I didn't have time to try on a very fresh centos install tho.

Maybe I'll lower the auto heal interval, but def, that's the problem. Or I can leave it like that and starts the container manually. As you can see in the 4th message, starting sormas & postgres first and wait for the sormas container to be up and running will do it.

Of course, as the apache2 container was not mounting properly, the curl check couldn't work either.

Anyway, thanks for the explanations and feedback. I'll do further tests on a clean server and see what's happening! 👍

**Comment by licks0re** [comment]
Tom, you are right about the autoheal interval.

Instead, I changed :

```
  apache2:
(...)
      sormas:
        condition: service_started

```

And I delay the first check of auto heal so my sormas container has time to start and get a "healthy" status.

```

        # wait 0 seconds before first health check
      - AUTOHEAL_START_PERIOD=240

```

As you can see, the apache2 container is started and has a healthy status while the sormas container is still taggued as "unhealthy" (because it take time to have a healthy status.



```

[root@sormasdev01 SORMAS-Docker]# docker ps
CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS                     PORTS                                      NAMES
add7fcaf1e53        hzibraunschweig/sormas-apache2:2.3.0       "/tmp/vhost.conf.s..."   2 minutes ago       Up 2 minutes (healthy)     0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp   sormasdocker_apache2_1
fd023e1c29a3        hzibraunschweig/sormas-application:2.3.0   "/start-server.sh"       2 minutes ago       Up 2 minutes (unhealthy)   6048/tcp, 6080/tcp                         sormasdocker_sormas_1
20d156d277b9        hzibraunschweig/sormas-pg-dump:2.3.0       "/entrypoint.sh /u..."   2 minutes ago       Up 2 minutes                                                          sormasdocker_pg_dump_1
d0945b576b7c        willfarrell/autoheal                       "/docker-entrypoin..."   2 minutes ago       Up 2 minutes (healthy)                                                sormasdocker_autoheal_1
814b8cc2490a        hzibraunschweig/sormas-postgres:2.3.0      "docker-entrypoint..."   2 minutes ago       Up 2 minutes (healthy)     0.0.0.0:5432->5432/tcp                     sormasdocker_postgres_1

```
