### ISSUE TITLE
Docker website username and password

### ISSUE THREAD

**Issue by cloe64** [hzi-braunschweig/SORMAS-Docker#6]
Have installed sormas-docker on Linux server, and was able to pop the website interface. What is default username and password to login the website?

**Comment by RafaelKluender** [comment]
Could you shortly resume how you did it? I followed the instructions, sormas is running on serverside but the website does not show up.

**Comment by TomHutter** [comment]
You find the default passwords for the sormas application here:
https://github.com/hzi-braunschweig/SORMAS-Project/blob/development/SERVER_UPDATE.md
