### ISSUE TITLE
Email Configuration

### ISSUE THREAD

**Issue by saurbhgupta29** [hzi-braunschweig/SORMAS-Docker#71]
What parameters to use/change for email server configuration?

**Comment by nk-designz** [comment]
Hi @saurbhgupta29,

thank you for showing interest into this project.
All configuration is done in the ```.env```-File.
For the mailing-stuff you might have a look at this section:
```ini
MAIL_HOST=localhost
EMAIL_SENDER_ADDRESS=noreply@sormas-docker-test.com
EMAIL_SENDER_NAME=SORMAS
```
Have  a nice day 🌱
