### ISSUE TITLE
Using Docker on Windows (WSL2)

### ISSUE THREAD

**Issue by saurav-bhattarai** [hzi-braunschweig/SORMAS-Docker#84]
I've running into issues on Docker on Windows 10 with WSL2. I believe the containers are all running properly, but just cannot access SORMAS from the browser - I keep getting 'this site cannot be reached' on the browser. I've tried accessing it as sormas-docker-test.com, as localhost, or even the internal IP of the WSL2. 

When I try to access it from the internal IP of the WSL2, I get redirected to sormas-docker-test.com/sormas-ui/, but nothing loads.

I'm using Docker 19.03.12

**Comment by asohh** [comment]
Hey,

did you add an entry to your hosts file (c:\windows\system32\drivers\etc\hosts)?

**Comment by saurav-bhattarai** [comment]
This worked! Thanks for the support. 

I had added an entry to the /etc/hosts within the WSL2, but didn't do it for the host Windows system.
