### ISSUE TITLE
'latest' tag for docker images

### ISSUE THREAD

**Issue by JonasCir** [hzi-braunschweig/SORMAS-Docker#88]
Hi,
we are working on a simple dev setup  https://github.com/hzi-braunschweig/SORMAS-Project/pull/2734 which pulls in the `sormas-postgres` image. Right now we have to stick to the explicit version tags which we need to update after each release. Is there a way to tag all SORMAS docker images with the default `latest` tag?
Thank you and best!

**Comment by asohh** [comment]
Hey,

with the next release all containerimages will receive a latest tag.

**Comment by JonasCir** [comment]
@asohh Great, thank you!
